### ISSUE TITLE
Please consider moving the Dockerfile to the root directory

### ISSUE THREAD

**Issue by AkbarTheGreat** [metio/matrix-alertmanager-receiver#41]
Docker's buildkit allows clean builds of git repositories inline via something like `docker build https://github.com/metio/matrix-alertmanager-receiver.git` -- but (as far as I'm aware) this only works if the Dockerfile is co-located with the root of the context.  Since the Dockerfile is written assuming a context of root-of-project, it's conventional to place the file there as well.

(The Dockerfile is also currently broken due to using the wrong Golang version, but that's a separate issue)

Thanks for your consideration, even if you opt not to move the file.

**Comment by sebhoss** [comment]
Yeah I'll do that - or if you like, you can open a PR?

**Comment by AkbarTheGreat** [comment]
Sure thing!

**Comment by sebhoss** [comment]
yep no prob! The dockerfile is referenced in the "release" workflow github action as well and needs adjustment when the file is moved

**Comment by sebhoss** [comment]
Fixed in #42 - thanks again!

**Comment by AkbarTheGreat** [comment]
Thank you!
